local spell_data_class = _G.spell_data
local spell_data_module = {}
function spell_data_module.create_spell_data(radius, range, cast_delay, projectile_speed, has_wall_collision, spell_id,
                                             geometry_type, targeting_type)
    return spell_data_class:new(radius, range, cast_delay, projectile_speed, has_wall_collision, spell_id,
        geometry_type or spell_geometry.rectangular, targeting_type or targeting_type.skillshot)
end

local spell_data = {
    holy_bolt = {
        spell_id = 2174078,
        category = "basic",
        cast_type = "target",
        damage_type = "holy",
        faith_gen = 16,
        cast_delay = 0.1,
        data = spell_data_module.create_spell_data(0.7, 15.0, 0.1, 2.0, true, 2174078, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    zeal = {
        spell_id = 2132824,
        category = "core",
        cast_type = "target",
        damage_type = "physical",
        faith_cost = 20,
        cast_delay = 0.15,
        data = spell_data_module.create_spell_data(0.7, 5.0, 0.15, 0.0, false, 2132824, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    advance = {
        spell_id = 2329865,
        category = "basic",
        cast_type = "position",
        damage_type = "physical",
        faith_gen = 18,
        cast_delay = 0.2,
        is_mobility = true,
        data = spell_data_module.create_spell_data(1.0, 6.0, 0.2, 15.0, false, 2329865, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    clash = {
        spell_id = 2097465,
        category = "basic",
        cast_type = "target",
        damage_type = "physical",
        faith_gen = 20,
        cast_delay = 0.15,
        requires_shield = true,
        data = spell_data_module.create_spell_data(1.0, 2.5, 0.15, 0.0, false, 2097465, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    brandish = {
        spell_id = 2265693,
        category = "basic",
        cast_type = "target",
        damage_type = "holy",
        faith_gen = 14,
        cast_delay = 0.15,
        data = spell_data_module.create_spell_data(1.5, 3.0, 0.15, 0.0, false, 2265693, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    blessed_hammer = {
        spell_id = 2107555,
        category = "core",
        cast_type = "self",
        damage_type = "holy",
        faith_cost = 10,
        cast_delay = 0.1,
        data = spell_data_module.create_spell_data(1.0, 5.0, 0.1, 5.0, false, 2107555, spell_geometry.circular,
            targeting_type.skillshot),
    },
    blessed_shield = {
        spell_id = 2082021,
        category = "core",
        cast_type = "target",
        damage_type = "holy",
        faith_cost = 28,
        cast_range = 6.0,
        cast_delay = 0.2,
        requires_shield = true,
        data = spell_data_module.create_spell_data(0.8, 6.0, 0.2, 10.0, true, 2082021, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    divine_lance = {
        spell_id = 2120228,
        category = "core",
        cast_type = "target",
        damage_type = "holy",
        faith_cost = 25,
        cast_delay = 0.2,
        is_mobility = true,
        data = spell_data_module.create_spell_data(0.7, 8.0, 0.2, 0.0, false, 2120228, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    shield_bash = {
        spell_id = 2087548,
        category = "core",
        cast_type = "target",
        damage_type = "physical",
        faith_cost = 32,
        cast_delay = 0.3,
        is_mobility = true,
        data = spell_data_module.create_spell_data(1.0, 6.0, 0.3, 12.0, false, 2087548, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    defiance_aura = {
        spell_id = 2187578,
        buff_id = 2187578,
        buff_name_patterns = { "defiance", "resolve" },
        category = "aura",
        cast_type = "self",
        faith_cost = 25,
        cooldown = 20.0,
        cast_delay = 0.1,
    },
    fanaticism_aura = {
        spell_id = 2187741,
        buff_id = 2187741,
        buff_name_patterns = { "fanatic", "fanaticism" },
        category = "aura",
        cast_type = "self",
        duration = 12.0,
        cast_delay = 0.1,
    },
    holy_light_aura = {
        spell_id = 2297097,
        buff_id = 2297097,
        buff_name_patterns = { "holy_light", "holylight", "light_aura" },
        category = "aura",
        cast_type = "self",
        damage_type = "holy",
        cooldown = 25.0,
        duration = 12.0,
        cast_delay = 0.1,
    },
    shield_charge = {
        spell_id = 2466077,
        category = "valor",
        cast_type = "position",
        damage_type = "physical",
        cast_delay = 0.3,
        data = spell_data_module.create_spell_data(1.5, 8.0, 0.3, 12.0, false, 2466077, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    rally = {
        spell_id = 2303677,
        category = "valor",
        cast_type = "self",
        charges = 3,
        cooldown = 16.0,
        faith_gen = 22,
        cast_delay = 0.1,
    },
    spear_of_the_heavens = {
        spell_id = 2100457,
        category = "justice",
        cast_type = "position",
        damage_type = "holy",
        cooldown = 14.0,
        cast_delay = 0.4,
        data = spell_data_module.create_spell_data(3.0, 10.0, 0.4, 0.0, false, 2100457, spell_geometry.circular,
            targeting_type.skillshot),
    },
    falling_star = {
        spell_id = 2106904,
        category = "justice",
        cast_type = "position",
        cast_delay = 0.6,
        data = spell_data_module.create_spell_data(4.0, 10.0, 0.6, 15.0, false, 2106904, spell_geometry.circular,
            targeting_type.skillshot),
    },
    condemn = {
        spell_id = 2226109,
        category = "justice",
        cast_type = "self",
        damage_type = "holy",
        cooldown = 15.0,
        cast_delay = 0.2,
        data = spell_data_module.create_spell_data(8.0, 0.0, 0.2, 0.0, false, 2226109, spell_geometry.circular,
            targeting_type.skillshot),
    },
    consecration = {
        spell_id = 2283781,
        category = "justice",
        cast_type = "self",
        damage_type = "holy",
        cooldown = 18.0,
        duration = 6.0,
        is_defensive = true,
        cast_delay = 0.2,
        data = spell_data_module.create_spell_data(5.0, 0.0, 0.2, 0.0, false, 2283781, spell_geometry.circular,
            targeting_type.skillshot),
    },
    purify = {
        spell_id = 2261380,
        category = "justice",
        cast_type = "self",
        cooldown = 12.0,
        cast_delay = 0.1,
    },
    arbiter_of_justice = {
        spell_id = 2297125,
        category = "ultimate",
        cast_type = "position",
        damage_type = "holy",
        cooldown = 120.0,
        cast_delay = 1.0,
        data = spell_data_module.create_spell_data(5.0, 12.0, 1.0, 15.0, false, 2297125, spell_geometry.circular,
            targeting_type.skillshot),
    },
    heavens_fury = {
        spell_id = 2273081,
        category = "ultimate",
        cast_type = "self",
        damage_type = "holy",
        cooldown = 30.0,
        cast_delay = 0.5,
        data = spell_data_module.create_spell_data(6.0, 0.0, 0.5, 0.0, false, 2273081, spell_geometry.circular,
            targeting_type.skillshot),
    },
    zenith = {
        spell_id = 2302974,
        category = "ultimate",
        cast_type = "self",
        cast_delay = 0.4,
        data = spell_data_module.create_spell_data(4.0, 0.0, 0.4, 0.0, false, 2302974, spell_geometry.circular,
            targeting_type.skillshot),
    },
    aegis = {
        spell_id = 2292204,
        category = "ultimate",
        cast_type = "self",
        cast_delay = 0.1,
    },
    fortress = {
        spell_id = 2301078,
        category = "ultimate",
        cast_type = "self",
        cooldown = 60.0,
        cast_delay = 0.1,
    },
    evade = {
        spell_id = 337031,
        category = "common",
        cast_type = "position",
        cast_delay = 0.5,
        is_mobility = true,
        data = spell_data_module.create_spell_data(0.5, 5.0, 0.5, 20.0, false, 337031, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    paladin_evade = {
        spell_id = 2256888,
        category = "common",
        cast_type = "position",
        is_mobility = true,
        cast_delay = 0.1,
        data = spell_data_module.create_spell_data(0.5, 5.0, 0.1, 25.0, false, 2256888, spell_geometry.rectangular,
            targeting_type.skillshot),
    },
    in_combat_area = {
        spell_id = 1271767,
        buff_id = 844134919
    },
    enemies = {
        damage_resistance = {
            spell_id = 1094180,
            buff_ids = {
                provider = 2771801864,
                receiver = 2182649012
            }
        }
    },
}
for k, v in pairs(spell_data_module) do spell_data[k] = v end
return spell_data
